In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pickle, copy
from collections import defaultdict
from Networkmodel import NetworkModel_org, HopField

In [2]:
class NetworkModel(NetworkModel_org):
    def task_condition(self):
        self.HFregister = dict()
        self.actdict = {1: [2], 2: [3,4], 3: [2], 4: [1]}  
        self.initial = 1
        self.terminal = [4]
        self.stmdict = {1: [1], 2: [2], 3: [3], 4:[4]}
        self.cortex_calc = [1]
        self.stmindex = {1:0, 2:0, 3:0, 4:0}
        self.swblock = 20
        for key,val in self.stmdict.items():
            for s in val:
                tmp = np.zeros(self.nstm)
                tmp[np.sort(np.random.choice(len(tmp), int(len(tmp)/2), replace = False))] = 1  
                self.HFregister[s] = tmp
                
    def check_rwd(self, result, count):
        if not result[-1]["cond"] in self.terminal:
            return 0
        swmode = np.mod(np.floor(count/self.swblock),2)
        tmp1 = sum([result[i]["infcond"] for i in range(len(result))], [])
        tmp2 = [result[i]["cond"] for i in range(len(result))]
        cnt1,cnt2 = len(np.where(np.array(tmp1)==3)[0]),len(np.where(np.array(tmp2)==3)[0])
        if count < self.swblock:
            return int(cnt1 + cnt2 == 0)
        elif count < self.swblock*2:
            return int(0 < cnt1 < 3 or 0 < cnt2 < 2) #int(cnt1 + cnt2 > 0)
        else:
            return int(2 < cnt1 or 1 < cnt2) #int(2 < cnt1 < 5 or 1 < cnt2 < 3)

In [3]:
allresult = dict()
x = 0

In [4]:
hp = NetworkModel(200,1000,300,1200,8)
result = []
HCprev = []
cond = None
for i in range(80):
    result_,HCprev,cond = hp.process(i, HCprev, cond, verbose = True)
    result.append(result_)
#allresult[x] = result
x += 1

trial 0 stmindex 0 HCprev []
HCprev []
think 0-0 [222]
plan 1 [] 2
init 1 2
memo 1 0
HF2HC [141] 1-0
HC2HF [141] 1-0
pkup [141] 1-0
choose [1. 2.] [141 208]
HF2HC [141] 1-0
HC2HF [141] 1-0
HCprev [array([208], dtype=int64)]
think 0-0 [73]
plan 2 [] 4
init 2 4
memo 2 0
HF2HC [215] 2-0
HC2HF [215] 2-0
pkup [215] 2-0
choose [2. 4.] [215 142]
HC2HF [208] 2-0
HF2HC [215] 2-0
HC2HF [215] 2-0
HCprev [array([142], dtype=int64)]
think 0-0 [282]
plan 4 [] 1
init 4 1
memo 4 0
HF2HC [218] 4-0
HC2HF [218] 4-0
pkup [218] 4-0
choose [4. 1.] [218  42]
HC2HF [142] 4-0
HF2HC [218] 4-0
HC2HF [218] 4-0
check trans [4.0] {}
['c:1', 'n:2.0', 'e:0.0', 'i:[1.0]', 'c:[0.0]', 'p:[1.0, 2.0]', 'H:[141 208]', 'a:1-0', 'r:0']
['c:2', 'n:4.0', 'e:0.0', 'i:[2.0]', 'c:[0.0]', 'p:[2.0, 4.0]', 'H:[208 215 142]', 'a:2-0', 'r:0']
['c:4', 'n:1', 'e:0.0', 'i:[4.0, 1.0]', 'c:[0.0, -1.0]', 'p:[4.0, 1.0]', 'H:[142 218  42]', 'a:4-0', 'r:1', "p:['1-0', '2-0', '4-0']"]

trial 1 stmindex 0 HCprev 42
HCprev [array([42], dtype=int6

check trans [1.0, 2.0, 4.0, 1.0] {}
['c:1', 'n:4.0', 'e:0.9368865766993457', 'i:[1.0, 2.0, 4.0]', 'c:[0.0, 0.0, 0.0]', 'p:[1.0, 2.0, 4.0]', 'H:[ 42 141 208 215 142 218  42]', 'a:1-0', 'r:0']
['c:4', 'n:1', 'e:0.9368865766993457', 'i:[1.0, 2.0, 4.0]', 'c:[0.0, 0.0, 0.0]', 'p:[1.0, 2.0, 4.0]', 'H:[ 42 141 208 215 142 218  42]', 'a:4-0', 'r:1', "p:['1-0', '2-0', '4-0']"]

trial 18 stmindex 0 HCprev 42
HCprev [array([42], dtype=int64)]
think 1-0 [141]
choose [1. 2. 4.] [141 208 215 142 218  42]
HC2HF [42] 1-0
HF2HC [141] 1-0
HC2HF [141] 1-0
tested ['1.0-0', '2.0-0', '4.0-0']
check trans [1.0, 2.0, 4.0, 1.0] {}
['c:1', 'n:4.0', 'e:0.9463535901944439', 'i:[1.0, 2.0, 4.0]', 'c:[0.0, 0.0, 0.0]', 'p:[1.0, 2.0, 4.0]', 'H:[ 42 141 208 215 142 218  42]', 'a:1-0', 'r:0']
['c:4', 'n:1', 'e:0.9463535901944439', 'i:[1.0, 2.0, 4.0]', 'c:[0.0, 0.0, 0.0]', 'p:[1.0, 2.0, 4.0]', 'H:[ 42 141 208 215 142 218  42]', 'a:4-0', 'r:1', "p:['1-0', '2-0', '4-0']"]

trial 19 stmindex 0 HCprev 42
HCprev [array([42], 

choose [1. 2. 3. 2. 4.] [141 208 215 222  15  77  33  66 114 153]
HC2HF [153] 1-0
HF2HC [141] 1-0
HC2HF [141] 1-0
tested ['4.0-0', '3.0-0', '2.0-0', '2.0-1', '4.0-1', '1.0-0']
check trans [1.0, 2.0, 3.0, 2.0, 4.0, 1.0] {(4.0, 0.0): 1.0}
['c:1', 'n:4.0', 'e:0.8031255956592774', 'i:[1.0, 2.0, 3.0, 2.0, 4.0]', 'c:[0.0, 0.0, 0.0, 1.0, 1.0]', 'p:[1.0, 2.0, 3.0, 2.0, 4.0]', 'H:[153 141 208 215 222  15  77  33  66 114 153]', 'a:1-0', 'r:0']
['c:4', 'n:1', 'e:0.8031255956592774', 'i:[1.0, 2.0, 3.0, 2.0, 4.0]', 'c:[0.0, 0.0, 0.0, 1.0, 1.0]', 'p:[1.0, 2.0, 3.0, 2.0, 4.0]', 'H:[153 141 208 215 222  15  77  33  66 114 153]', 'a:4-1', 'r:1', "p:['1-0', '2-0', '4-0', '3-0', '2-1', '4-1']"]

trial 32 stmindex 0 HCprev 153
HCprev [array([153], dtype=int64)]
think 1-0 [141]
choose [1. 2. 3. 2. 4.] [141 208 215 222  15  77  33  66 114 153]
HC2HF [153] 1-0
HF2HC [141] 1-0
HC2HF [141] 1-0
tested ['4.0-0', '3.0-0', '2.0-0', '2.0-1', '4.0-1', '1.0-0']
check trans [1.0, 2.0, 3.0, 2.0, 4.0, 1.0] {(4.0, 0.0): 

plan 2 [4] 3
actremapping [141 208 215 222  15  77  33  66] [141 208 215 222  15  77  33 267]
choose [1. 2. 3. 2. 3.] [141 208 215 222  15  77  33 267]
HC2HF [153] 1-0
HF2HC [141] 1-0
HC2HF [141] 1-0
HCprev [array([267], dtype=int64)]
think 0-0 [201]
plan 3 [] 2
init 3 2
memo 3 1
HF2HC [230] 3-1
HC2HF [230] 3-1
pkup [230] 3-1
choose [3. 2.] [230 212]
HC2HF [267] 3-1
HF2HC [230] 3-1
HC2HF [230] 3-1
HCprev [array([212], dtype=int64)]
think 0-0 [74]
plan 2 [] 4
init 2 4
memo 2 2
HF2HC [192] 2-2
HC2HF [192] 2-2
pkup [192] 2-2
choose [2. 4.] [192  60]
HC2HF [212] 2-2
HF2HC [192] 2-2
HC2HF [192] 2-2
HCprev [array([60], dtype=int64)]
think 0-0 [7]
plan 4 [] 1
init 4 1
memo 4 2
HF2HC [204] 4-2
HC2HF [204] 4-2
pkup [204] 4-2
choose [4. 1.] [204 248]
HC2HF [60] 4-2
HF2HC [204] 4-2
HC2HF [204] 4-2
check trans [4.0] {(4.0, 0.0): 1.043, (4.0, 1.0): 1.49}
['c:1', 'n:3.0', 'e:0', 'i:[1.0, 2.0, 3.0, 2.0]', 'c:[0.0, 0.0, 0.0, 1.0]', 'p:[1.0, 2.0, 3.0, 2.0, 3.0]', 'H:[153 141 208 215 222  15  77  33 267

choose [1. 2. 3. 2. 3. 2. 4.] [141 208 215 222  15  77  33 267 230 212 192  60 204 248]
HC2HF [248] 1-0
HF2HC [141] 1-0
HC2HF [141] 1-0
check trans [1.0, 2.0, 3.0, 2.0, 3.0, 2.0, 4.0, 1.0] {(4.0, 0.0): 1.043, (4.0, 1.0): 1.49}
['c:1', 'n:4.0', 'e:0.622850484375', 'i:[1.0, 2.0, 3.0, 2.0, 3.0, 2.0, 4.0]', 'c:[0.0, 0.0, 0.0, 1.0, 1.0, 2.0, 2.0]', 'p:[1.0, 2.0, 3.0, 2.0, 3.0, 2.0, 4.0]', 'H:[248 141 208 215 222  15  77  33 267 230 212 192  60 204 248]', 'a:1-0', 'r:0']
['c:4', 'n:1', 'e:0.622850484375', 'i:[1.0, 2.0, 3.0, 2.0, 3.0, 2.0, 4.0]', 'c:[0.0, 0.0, 0.0, 1.0, 1.0, 2.0, 2.0]', 'p:[1.0, 2.0, 3.0, 2.0, 3.0, 2.0, 4.0]', 'H:[248 141 208 215 222  15  77  33 267 230 212 192  60 204 248]', 'a:4-2', 'r:1', "p:['1-0', '2-0', '4-0', '3-0', '2-1', '4-1', '3-1', '2-2', '4-2']"]

trial 51 stmindex 0 HCprev 248
HCprev [array([248], dtype=int64)]
think 1-0 [141]
choose [1. 2. 3. 2. 3. 2. 4.] [141 208 215 222  15  77  33 267 230 212 192  60 204 248]
HC2HF [248] 1-0
HF2HC [141] 1-0
HC2HF [141] 1-0
c

check trans [1.0, 2.0, 3.0, 2.0, 3.0, 2.0, 4.0, 1.0] {(4.0, 0.0): 1.043, (4.0, 1.0): 1.49}
['c:1', 'n:4.0', 'e:0.9257489137639361', 'i:[1.0, 2.0, 3.0, 2.0, 3.0, 2.0, 4.0]', 'c:[0.0, 0.0, 0.0, 1.0, 1.0, 2.0, 2.0]', 'p:[1.0, 2.0, 3.0, 2.0, 3.0, 2.0, 4.0]', 'H:[248 141 208 215 222  15  77  33 267 230 212 192  60 204 248]', 'a:1-0', 'r:0']
['c:4', 'n:1', 'e:0.9257489137639361', 'i:[1.0, 2.0, 3.0, 2.0, 3.0, 2.0, 4.0]', 'c:[0.0, 0.0, 0.0, 1.0, 1.0, 2.0, 2.0]', 'p:[1.0, 2.0, 3.0, 2.0, 3.0, 2.0, 4.0]', 'H:[248 141 208 215 222  15  77  33 267 230 212 192  60 204 248]', 'a:4-2', 'r:1', "p:['1-0', '2-0', '4-0', '3-0', '2-1', '4-1', '3-1', '2-2', '4-2']"]

trial 61 stmindex 0 HCprev 248
HCprev [array([248], dtype=int64)]
think 1-0 [141]
choose [1. 2. 3. 2. 3. 2. 4.] [141 208 215 222  15  77  33 267 230 212 192  60 204 248]
HC2HF [248] 1-0
HF2HC [141] 1-0
HC2HF [141] 1-0
tested ['4.0-0', '3.0-0', '2.0-2', '2.0-0', '2.0-1', '4.0-1', '1.0-0', '3.0-1', '4.0-2']
check trans [1.0, 2.0, 3.0, 2.0, 3.0, 2.

choose [1. 2. 3. 2. 3. 2. 4.] [141 208 215 222  15  77  33 267 230 212 192  60 204 248]
HC2HF [248] 1-0
HF2HC [141] 1-0
HC2HF [141] 1-0
tested ['4.0-0', '3.0-0', '2.0-2', '2.0-0', '2.0-1', '4.0-1', '1.0-0', '3.0-1', '4.0-2']
check trans [1.0, 2.0, 3.0, 2.0, 3.0, 2.0, 4.0, 1.0] {(4.0, 0.0): 1.043, (4.0, 1.0): 1.49}
['c:1', 'n:4.0', 'e:0.9875745823817799', 'i:[1.0, 2.0, 3.0, 2.0, 3.0, 2.0, 4.0]', 'c:[0.0, 0.0, 0.0, 1.0, 1.0, 2.0, 2.0]', 'p:[1.0, 2.0, 3.0, 2.0, 3.0, 2.0, 4.0]', 'H:[248 141 208 215 222  15  77  33 267 230 212 192  60 204 248]', 'a:1-0', 'r:0']
['c:4', 'n:1', 'e:0.9875745823817799', 'i:[1.0, 2.0, 3.0, 2.0, 3.0, 2.0, 4.0]', 'c:[0.0, 0.0, 0.0, 1.0, 1.0, 2.0, 2.0]', 'p:[1.0, 2.0, 3.0, 2.0, 3.0, 2.0, 4.0]', 'H:[248 141 208 215 222  15  77  33 267 230 212 192  60 204 248]', 'a:4-2', 'r:1', "p:['1-0', '2-0', '4-0', '3-0', '2-1', '4-1', '3-1', '2-2', '4-2']"]

trial 72 stmindex 0 HCprev 248
HCprev [array([248], dtype=int64)]
think 1-0 [141]
choose [1. 2. 3. 2. 3. 2. 4.] [141 208 2

In [5]:
num = 40
trialnum = 80
allresult = dict() #np.zeros((num,trialnum))*np.nan
x = 0
errcounter = 0
while x < num:
    print(x)
    hp = NetworkModel(200,1000,300,1200,8)
    result = []
    HCprev = []
    cond = None
    try:
        for i in range(trialnum):
            result_,HCprev,cond = hp.process(i, HCprev, cond,verbose = False)
            result.append(result_)
        allresult[x] = result
    except:
        print("error",x)
        allresult[x] = result
        errcounter += 1
    x += 1
print(errcounter)

0
init 1 2
init 2 3
init 3 2
init 2 4
init 4 1
actremapping [157   7] [157 175]
init 4 1
set NG [4. 1.] {(4.0, 1.0): 1.0}
actremapping [79 47] [79 52]
init 3 2
init 2 4
init 4 1
actremapping [ 23 215] [ 23 170]
init 3 2
init 2 4
init 4 1
actremapping [54 58] [ 54 239]
init 3 2
init 2 4
init 4 1
actremapping [275 237] [275 120]
init 3 2
init 2 4
init 4 1
set NG [4. 1.] {(4.0, 1.0): 1.0}
init 2 4
init 4 1
1
init 1 2
init 2 3
init 3 2
init 2 4
init 4 1
actremapping [82 55] [ 82 155]
init 3 2
init 2 4
init 4 1
actremapping [ 8 34] [ 8 14]
init 3 2
init 2 4
init 4 1
actremapping [198 165] [198  29]
init 4 1
set NG [4. 3.] {(4.0, 3.0): 1.0}
set NG [4. 0.] {(4.0, 0.0): 1.0, (4.0, 3.0): 0.7}
set NG [4. 3.] {(4.0, 0.0): 0.7, (4.0, 3.0): 1.49}
set NG [4. 0.] {(4.0, 0.0): 1.49, (4.0, 3.0): 1.043}
set NG [4. 3.] {(4.0, 0.0): 1.043, (4.0, 3.0): 1.7300999999999997}
set NG [4. 0.] {(4.0, 0.0): 1.7300999999999997, (4.0, 3.0): 1.2110699999999996}
set NG [4. 3.] {(4.0, 0.0): 1.2110699999999996, (4.0, 3.

set NG [4. 3.] {(4.0, 0.0): 1.2934242999999999, (4.0, 3.0): 1.9053970099999997}
set NG [4. 0.] {(4.0, 0.0): 1.9053970099999997, (4.0, 3.0): 1.3337779069999998}
set NG [4. 3.] {(4.0, 0.0): 1.3337779069999998, (4.0, 3.0): 1.9336445348999998}
set NG [4. 0.] {(4.0, 0.0): 1.9336445348999998, (4.0, 3.0): 1.3535511744299997}
set NG [4. 3.] {(4.0, 0.0): 1.3535511744299997, (4.0, 3.0): 1.9474858221009996}
9
init 1 2
init 2 4
init 4 1
set NG [4. 0.] {(4.0, 0.0): 1.0}
actremapping [215  25  11 247] [215  25  11  28]
init 3 2
init 2 4
init 4 1
set NG [4. 1.] {(4.0, 0.0): 0.7, (4.0, 1.0): 1.0}
set NG [4. 0.] {(4.0, 0.0): 1.49, (4.0, 1.0): 0.7}
set NG [4. 1.] {(4.0, 0.0): 1.043, (4.0, 1.0): 1.49}
set NG [4. 0.] {(4.0, 0.0): 1.7300999999999997, (4.0, 1.0): 1.043}
actremapping [215  25  11  28   1  44  58 264] [215  25  11  28   1  44  58 122]
init 3 2
init 2 4
init 4 1
set NG [4. 1.] {(4.0, 0.0): 1.2110699999999996, (4.0, 1.0): 1.7300999999999997}
set NG [4. 0.] {(4.0, 0.0): 1.8477489999999999, (4.0,

init 2 3
init 3 2
init 2 4
init 4 1
set NG [4. 1.] {(4.0, 1.0): 1.0, (4.0, 0.0): 1.043}
set NG [4. 1.] {(4.0, 1.0): 1.0, (4.0, 0.0): 0.7300999999999999}
actremapping [223 254] [223 136]
init 4 1
set NG [4. 0.] {(4.0, 1.0): 0.7, (4.0, 0.0): 1.51107}
set NG [4. 1.] {(4.0, 1.0): 1.49, (4.0, 0.0): 1.0577489999999998}
set NG [4. 0.] {(4.0, 1.0): 1.043, (4.0, 0.0): 1.7404243}
set NG [4. 1.] {(4.0, 1.0): 1.7300999999999997, (4.0, 0.0): 1.21829701}
set NG [4. 0.] {(4.0, 1.0): 1.2110699999999996, (4.0, 0.0): 1.8528079069999999}
set NG [4. 1.] {(4.0, 1.0): 1.8477489999999999, (4.0, 0.0): 1.2969655348999998}
set NG [4. 0.] {(4.0, 1.0): 1.2934242999999999, (4.0, 0.0): 1.9078758744299997}
set NG [4. 1.] {(4.0, 1.0): 1.9053970099999997, (4.0, 0.0): 1.3355131121009998}
set NG [4. 0.] {(4.0, 1.0): 1.3337779069999998, (4.0, 0.0): 1.9348591784706999}
18
init 1 2
init 2 4
init 4 1
set NG [4. 0.] {(4.0, 0.0): 1.0}
actremapping [110 257 268  10] [110 257 268 188]
init 3 2
init 2 4
init 4 1
set NG [4. 1.] {

26
init 1 2
init 2 3
init 3 2
init 2 4
init 4 1
actremapping [263 232] [263  76]
init 4 1
set NG [4. 1.] {(4.0, 1.0): 1.0}
set NG [4. 0.] {(4.0, 1.0): 0.7, (4.0, 0.0): 1.0}
set NG [4. 1.] {(4.0, 1.0): 1.49, (4.0, 0.0): 0.7}
set NG [4. 0.] {(4.0, 1.0): 1.043, (4.0, 0.0): 1.49}
set NG [4. 1.] {(4.0, 1.0): 1.7300999999999997, (4.0, 0.0): 1.043}
actremapping [169 186 263 232  70 288  79 203] [169 186 263 232  70 288  79  31]
init 3 2
init 2 3
init 3 2
init 2 4
init 4 1
actremapping [ 66 135] [ 66 198]
init 4 1
set NG [4. 0.] {(4.0, 1.0): 1.2110699999999996, (4.0, 0.0): 1.7300999999999997}
set NG [4. 1.] {(4.0, 1.0): 1.8477489999999999, (4.0, 0.0): 1.2110699999999996}
set NG [4. 0.] {(4.0, 1.0): 1.2934242999999999, (4.0, 0.0): 1.8477489999999999}
27
init 1 2
init 2 4
init 4 1
set NG [4. 0.] {(4.0, 0.0): 1.0}
actremapping [ 18 293  64 225] [ 18 293  64  92]
init 3 2
init 2 4
init 4 1
set NG [4. 1.] {(4.0, 0.0): 0.7, (4.0, 1.0): 1.0}
set NG [4. 0.] {(4.0, 0.0): 1.49, (4.0, 1.0): 0.7}
set NG [

34
init 1 2
init 2 4
init 4 1
set NG [4. 0.] {(4.0, 0.0): 1.0}
actremapping [ 31  48  79 278] [31 48 79 95]
init 3 2
init 2 4
init 4 1
set NG [4. 1.] {(4.0, 0.0): 0.7, (4.0, 1.0): 1.0}
set NG [4. 0.] {(4.0, 0.0): 1.49, (4.0, 1.0): 0.7}
set NG [4. 1.] {(4.0, 0.0): 1.043, (4.0, 1.0): 1.49}
set NG [4. 0.] {(4.0, 0.0): 1.7300999999999997, (4.0, 1.0): 1.043}
actremapping [ 31  48  79  95  57  19 119 158] [ 31  48  79  95  57  19 119 194]
init 3 2
init 2 4
init 4 1
set NG [4. 1.] {(4.0, 0.0): 1.2110699999999996, (4.0, 1.0): 1.7300999999999997}
set NG [4. 0.] {(4.0, 0.0): 1.8477489999999999, (4.0, 1.0): 1.2110699999999996}
35
init 1 2
init 2 4
init 4 1
set NG [4. 0.] {(4.0, 0.0): 1.0}
actremapping [120 179  80  99] [120 179  80 296]
init 3 2
init 2 4
init 4 1
set NG [4. 1.] {(4.0, 0.0): 0.7, (4.0, 1.0): 1.0}
set NG [4. 0.] {(4.0, 0.0): 1.49, (4.0, 1.0): 0.7}
set NG [4. 1.] {(4.0, 0.0): 1.043, (4.0, 1.0): 1.49}
actremapping [120 179  80 296  49  98  48 196] [120 179  80 296  49  98  48 148]
in

set NG [4. 0.] {(4.0, 0.0): 1.04887104282949, (4.0, 1.0): 0.8477489999999998, (4.0, 6.0): 0.7}
actremapping [114 237] [114  65]
init 4 1
init 1 2
init 2 3
init 3 2
init 2 3
forget 3-9 [252] []
forget 3-12 [118] []
forget 3-10 [267] []
forget 3-13 [229] []
forget 3-8 [73] []
forget 3-11 [271] []
forget 3-14 [128] []
init 3 2
init 2 4
init 4 1
init 2 3
init 3 2
forget 2-15 [114] [97]
forget 2-16 [153] []
forget 2-17 [208] []
forget 2-21 [43] []
forget 2-18 [155] []
forget 2-20 [37] []
forget 2-19 [278] []
init 2 4
init 4 1
set NG [ 4. 11.] {(4.0, 0.0): 0.734209729980643, (4.0, 1.0): 0.5934242999999998, (4.0, 6.0): 0.48999999999999994, (4.0, 11.0): 1.0}
set NG [4. 0.] {(4.0, 0.0): 1.5139468109864502, (4.0, 1.0): 0.41539700999999984, (4.0, 6.0): 0.3429999999999999, (4.0, 11.0): 0.7}
set NG [ 4. 11.] {(4.0, 0.0): 1.059762767690515, (4.0, 1.0): 0.2907779069999999, (4.0, 6.0): 0.24009999999999992, (4.0, 11.0): 1.49}
actremapping [274 139 251  97  63 155] [274 139 251  97  63 104]
init 3 2
ini

In [6]:
test

[array([600]),
 array([600]),
 array([600]),
 array([600]),
 array([600]),
 array([600]),
 array([600]),
 array([600]),
 array([600]),
 array([600]),
 array([600]),
 array([600]),
 array([600]),
 array([600]),
 array([600]),
 array([600]),
 array([600]),
 array([600]),
 array([600]),
 array([600]),
 array([600]),
 array([600]),
 array([600]),
 array([600]),
 array([600]),
 array([600]),
 array([600]),
 array([600]),
 array([600]),
 array([600]),
 array([600]),
 array([600]),
 array([600]),
 array([600]),
 array([600]),
 array([600]),
 array([600]),
 array([600]),
 array([600]),
 array([357, 359, 360, 361, 364, 600])]

In [ ]:
with open("./pkls/dropby_2times.pkl", mode = "wb") as f:
    pickle.dump(allresult, f)

In [ ]:
with open("./pkls/dropby_2times.pkl", mode = "rb") as f:
    allresult = pickle.load(f)
num = len(allresult)
trialnum = np.max([len(allresult[x]) for x in range(num)])

In [ ]:
rwdrate = np.zeros((num,trialnum))
for x in range(num):
    tmp = [res[-1]["rwd"] for r, res in enumerate(allresult[x])]
    rwdrate[x,:len(tmp)] = tmp

In [ ]:
plt.imshow(rwdrate)

In [ ]:
plt.figure(figsize = (10,4))
for i in range(1,int(trialnum/hp.swblock)-1):
    plt.plot([hp.swblock*i-0.5,hp.swblock*i-0.5], [-5,105], "--",color = "#555555")
plt.errorbar(np.arange(trialnum), np.nanmean(rwdrate,0)*100, 100*np.nanstd(rwdrate,0)/np.sqrt(num),fmt="go-")
plt.xlabel("trial index", fontsize = 20)
plt.ylabel("correct [%]", fontsize = 20)
plt.xticks(np.arange(-0.5,trialnum+1,20),np.arange(0,trialnum+1,20), fontsize = 15)
plt.yticks(fontsize = 15) 
plt.ylim([-5,105])
plt.savefig("./figure/dropby_2times_correct.png", bbox_inches = "tight")

In [ ]:
inflen = np.zeros((num,trialnum))*np.nan
for x in range(num):
    tmp = [int((len(allresult[x][r][-1]["HCtrans"])-1)/2) for r in range(len(allresult[x]))]
    inflen[x,:len(tmp)] = tmp

In [ ]:
plt.figure(figsize = (10,4))
for i in range(1,int(trialnum/hp.swblock)-1):
    plt.plot([hp.swblock*i-0.5,hp.swblock*i-0.5], [0,8], "--",color = "#555555")
for i in range(num):
    plt.plot(np.arange(trialnum), inflen[i,:]+np.random.rand(trialnum)*0, "ko-", linewidth = 0.3, markerfacecolor = (0,0,0,0.05))    
plt.plot(np.arange(trialnum), np.nanmean(inflen,0), "r")
plt.xlabel("trial index", fontsize = 20)
plt.ylabel("planning length", fontsize = 20)
plt.xticks(np.arange(-0.5,trialnum+1,20), np.arange(0,trialnum + 1,20), fontsize = 15)
plt.yticks(np.arange(1,8,2),fontsize = 15)
plt.ylim([.5,8])
plt.savefig("./figure/dropby_2times_inflen.png", bbox_inches = "tight")

In [ ]:
for x in range(2):
    allHCs, allinfs = [], []
    if len(allresult[x]) != trialnum:
        continue
    for y in range(trialnum):
        HCs = []
        for z in range(len(allresult[x][y])):
            tmp = copy.deepcopy(allresult[x][y][z]["HCtrans"])
            if len(tmp) % 2 == 1:
                tmp = tmp[1:]
            arg = np.isin(tmp, HCs)
            HCs.extend(list(tmp[~arg]))
            tmp = allresult[x][y][z]["infcond"]
            if z == 0:
                infs = copy.deepcopy(tmp)
            elif infs[-1] == tmp[0]:
                infs.extend(tmp[1:])
            elif infs[-1] == tmp[-1]:
                continue
            else:
                print(x,y,z,tmp, infs, len(HCs))
        if HCs[0] == HCs[-1]:
            HCs = HCs[:-1]
        if infs[0] == infs[-1]:
            infs = infs[:-1]
        HCs = HCs[:len(infs)*2]
        allHCs.append(HCs)
        allinfs.append(infs)

In [ ]:
mat = np.zeros((2*7, 7))
for i in range(7):
    mat[2*i:2*i+2,i] = 1

In [ ]:
plt.figure(figsize = (4,8))
plt.imshow(mat, cmap = "jet")
plt.plot(np.ones(2)*0.5,[-0.5,13.5], color = "#D648D6")
plt.plot(np.ones(2)*3,[-0.5,13.5], color = "#D648D6")
plt.plot(np.ones(2)*5.5,[-0.5,13.5], color = "#D648D6")
plt.tick_params(left = False, right = False , labelleft = False ,
                labelbottom = False, bottom = False)
plt.savefig("./figure/dropby_2times_firing.png", bbox_inches = "tight")